apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      nodeSelector:
        workload: gpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args: ["--model", "Qwen/Qwen2.5-0.5B-Instruct", "--gpu-memory-utilization", "0.8"]
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: default
  labels:
    app: vllm
spec:
  selector:
    app: vllm
  ports:
    - name: http        # <--- Added port name for Prometheus discovery
      protocol: TCP
      port: 8000
      targetPort: 8000